version: "3"

services:
  macronizer:
    build:
      context: .
    image: latin-macronizer
    depends_on:
      - postgres
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}

  postgres:
    image: postgres:13.11-bullseye
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      default:
        aliases:
          - postgres
